/*
 *crack.c
 *Balint Harmat
 *balinth.cg@gmail.com
 *attempts to crack a ciphertext, generated by "crypt(key, salt)" function
 */
#define _XOPEN_SOURCE
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <cs50.h>
/*for some reason it didnt work when I put the salt and cipher in a global variable, they werent visible inside the generate function*/
void generate(char* key, int current, char* salty, char* cipher);
int found = 1; /* 0, ha megvan...*/
char* test;

int main(int argc, string argv[])
{
    if (argc != 2)
    {
        printf("I need one ciphertext as a single argument!\n");
        return 1;
    }
    /* Read the cipher, and the salt*/
    char* cipher = argv[1];
    char* salty = malloc(3*sizeof(char));
    if (salty == NULL)
    {
        return 2;
    }
    for (int i = 0; i < 2; i++)
    {
        salty[i] = cipher[i];
    }
    salty[2] = 0;
    printf("Salt: %s\n", salty);
    char* key = malloc(8*sizeof(char));
    /* chow through the dictionary*/
    FILE* dict;
    dict = fopen("/usr/share/dict/words", "r");
    //while (found == 1)
    //{
        //*key = fscanf(dict, "%s", key);
        //printf("%s\n", key);
    //}
    //fclose(dict);
    
    
    
    /*for (int i = 0; i < 8; i++)
    {
        key[i] = 97;
    }*/
    generate(key, 0, salty, cipher);
    
    return 0;
}  

void generate(char* key, int current, char* salty, char* cipher)
{
    for (int i = 0; i < 26; i ++)
    {
        key[current] = 97 + i;
        if (key[current + 1] != 99 || key[current] != 97 + i)
        {
            if (found == 0)
            {
                return;
            }
            //printf("%s\n", key);
            char* test = malloc(14);
            test = crypt(key, salty);
            found = strcmp(cipher, test);
            if (found == 0)
            {
                printf("%s\n", key);
                return;
            }
        }
        if (found == 0)
        {
            return;
        }
        if (current < 7)
        {
            generate(key, current + 1, salty, cipher);
            
        }
    }
}
